
name: build-linux

on:
  workflow_call:

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - name: repo
        uses: actions/checkout@v3
        with:
          path: svl
          fetch-depth: 0

      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: git
        run: |
          git config --global user.email "apollo3-uploader-builder@sparkfun.com"
          git config --global user.name "apollo3-uploader-builder"
          git config --global pull.ff only
          cd svl
          git pull
          cd ${GITHUB_WORKSPACE}

      - name: install
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          pip install -r svl/requirements.txt

      - name: build
        run: |
          pyinstaller --onefile svl/svl.py

      - name: copy
        run: |
          rm -rf ./svl/dist/linux
          mkdir -p ./svl/dist/linux
          mv ./dist/svl ./svl/dist/linux/svl

      - name: permit
        run: |
          chmod +x ./svl/dist/linux/svl

      - name: commit
        run: |
          cd ./svl
          git add ./dist/linux/*
          git commit -m "generated linux executable"
          git push
          cd ${GITHUB_WORKSPACE}
